### ISSUE TITLE
Docker Hub image?

### ISSUE THREAD

**Issue by mohamed--abdel-maksoud** [jdrouet/docker-activity#130]
Would you please publish a dockerhub to make this project more accessible?

**Comment by dwphilbrick** [comment]
It is on [Dockerhub](https://hub.docker.com/r/jdrouet/docker-activity) but I am running into the issue "Error response from daemon: error while creating mount source path '/sys/class/powercap': mkdir /sys/class/powercap: operation not permitted.
ERRO[0087] error waiting for container:  " when running it...not sure if there is a limitation of my Linux device, or a premission error?

**Comment by jdrouet** [comment]
@mohamed--abdel-maksoud yes, it is on docker hub
@dwphilbrick check if your host has the folder `/sys/class/powercap` already. If not, it's because your device/OS is not compatible.

**Comment by mohamed--abdel-maksoud** [comment]
@dwphilbrick @jdrouet Thanks for the info, I didn't know it existed.
May I suggest it to be added to README? This is how most people would use it imho.
Thanks again!

**Comment by dwphilbrick** [comment]
@jdrouet im on Armbian 23.05.0 with Linux 5.15.1150 but I am not seeing a "sys" folder so it looks like I am out of luck!
